name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-image:
    name: 'Build image'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    outputs:
      image: ${{ steps.build.outputs.imageid }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4.1.6

      - name: 'Set up Docker Build'
        uses: docker/setup-buildx-action@v3.3.0

      - name: 'Build image'
        id: build
        uses: docker/build-push-action@v5.3.0
        with:
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=gha,ignore-error=true
          cache-to: type=gha,mode=max,ignore-error=true
          target: prod

      - name: 'Upload build'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: image
          path: /tmp/image.tar

  format:
    name: 'Format'
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4.1.6

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: ${{ !env.ACT && 'npm' || '' }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run formatter'
        run: npx prettier --ignore-unknown --check '**'
